statsInEnglish = {
    'age': 'Age'
    , 'ast': 'Total ast'
    , 'ast_per_g': 'Ast/g'
    , 'ast_per_mp': 'Ast/36min'
    , 'ast_per_poss': 'Ast/100poss'
    , 'blk': 'Total blk'
    , 'blk_per_g': 'Blk/g'
    , 'blk_per_mp': 'Blk/36min'
    , 'blk_per_poss': 'Blk/100poss'
    , 'def_rtg': 'DRtg'
    , 'drb': 'Total DReb'
    , 'drb_per_g': 'DReb/g'
    , 'drb_per_mp': 'DReb/36min'
    , 'drb_per_poss': 'DReb/100poss'
    , 'efg_pct': 'EFG%'
    , 'fg': 'FG made'
    , 'fg2': '2pt FG made'
    , 'fg2_pct': '2pt FG%'
    , 'fg2_per_g': '2pt FG/g'
    , 'fg2_per_mp': '2pt FG/36min'
    , 'fg2_per_poss': '2pt FG/100poss'
    , 'fg2a': '2pt FG att'
    , 'fg2a_per_g': '2pt FG att/g'
    , 'fg2a_per_mp': '2pt FG att/36min'
    , 'fg2a_per_poss': '2pt FG att/100poss'
    , 'fg3': '3pt FG made'
    , 'fg3_pct': '3pt FG%'
    , 'fg3_per_g': '3pt FG/g'
    , 'fg3_per_mp': '3pt FG/36min'
    , 'fg3_per_poss': '3pt FG/100poss'
    , 'fg3a': '3pt FG att'
    , 'fg3a_per_g': '3pt FG att/g'
    , 'fg3a_per_mp': '3pt FG att/36min'
    , 'fg3a_per_poss': '3pt FG att/100poss'
    , 'fg_pct': 'FG%'
    , 'fg_per_g': 'FG/g'
    , 'fg_per_mp': 'FG/36min'
    , 'fg_per_poss': 'FG/100poss'
    , 'fga': 'FGA'
    , 'fga_per_g': 'FGA/g'
    , 'fga_per_mp': 'FGA/36min'
    , 'fga_per_poss': 'FGA/100poss'
    , 'ft': 'FT made'
    , 'ft_pct': 'FT%'
    , 'ft_per_g': 'FT/g'
    , 'ft_per_mp': 'FT36min'
    , 'ft_per_poss': 'FT/100poss'
    , 'fta': 'FTA'
    , 'fta_per_g': 'FTA,g'
    , 'fta_per_mp': 'FTA/36min'
    , 'fta_per_poss': 'FTA/100poss'
    , 'g': 'Games played'
    , 'gs': 'Games started'
    , 'mp': 'Minutes played'
    , 'mp_per_g': 'Min/g'
    , 'off_rtg': 'ORtg'
    , 'orb': 'Total OReb'
    , 'orb_per_g': 'OReb/g'
    , 'orb_per_mp': 'OReb/36min'
    , 'orb_per_poss': 'OReb/100poss'
    , 'pf': 'Fouls'
    , 'pf_per_g': 'Fouls/g'
    , 'pf_per_mp': 'Fouls/36min'
    , 'pf_per_poss': 'Fouls/100poss'
    , 'player': 'Name'
    , 'pos': 'Pos'
    , 'pts': 'Total points'
    , 'pts_per_g': 'Pts/g'
    , 'pts_per_mp': 'Pts/36min'
    , 'pts_per_poss': 'Pts/100poss'
    , 'stats': ''
    , 'stl': 'Stl'
    , 'stl_per_g': 'Stl/g'
    , 'stl_per_mp': 'Stl/36min'
    , 'stl_per_poss': 'Stl/100poss'
    , 'team_id': 'Team'
    , 'tov': 'TO'
    , 'tov_per_g': 'TO/g'
    , 'tov_per_mp': 'TO/36min'
    , 'tov_per_poss': 'TO/100poss'
    , 'trb': 'Total Reb'
    , 'trb_per_g': 'Reb/g'
    , 'trb_per_mp': 'Reb/36min'
    , 'trb_per_poss': 'Reb/100poss'
}
